version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    networks:
      - my_network
    ports:
      - "8081:80"
    environment:
      PMA_HOST: '${MYSQL_HOST}'
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    networks:
      - my_network
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: '${MYSQL_HOST}:${MYSQL_PORT}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
    volumes:
      - ./wordpress:/var/www/html


  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    networks:
      - my_network
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress

networks:
  my_network:
    driver: bridge
